# Generated by Django 3.2.13 on 2022-12-01 07:20

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('song_url', models.CharField(max_length=400)),
                ('song_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
