# Generated by Django 3.2.13 on 2022-11-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='music_start',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
