# Generated by Django 3.2.13 on 2022-12-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='feelings',
            field=models.CharField(choices=[('😃', '😃'), ('😄', '😄'), ('🤣', '🤣'), ('😍', '😍'), ('🥴', '🥴'), ('🤪', '🤪'), ('😐', '😐'), ('🙄', '🙄'), ('😔', '😔'), ('😪', '😪'), ('😦', '😦'), ('😰', '😰'), ('😭', '😭'), ('😱', '😱'), ('😣', '😣'), ('😩', '😩'), ('😤', '😤'), ('🥱', '🥱'), ('🥵', '🥵'), ('🥶', '🥶')], max_length=10),
        ),
    ]
