# Generated by Django 3.2.13 on 2022-11-29 07:42

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(validators=[articles.models.validate_text]),
        ),
    ]
