# Generated by Django 3.2.13 on 2022-11-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='feelings',
            field=models.CharField(choices=[('👿', '👿'), ('😞', '😞'), ('😊', '😊')], max_length=2),
        ),
    ]
