# Generated by Django 3.2.13 on 2022-11-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_music_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='music_start',
            field=models.IntegerField(default=0),
        ),
    ]
