# Generated by Django 3.2.13 on 2022-12-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20221201_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='music_start',
            field=models.IntegerField(default=0),
        ),
    ]
