# Generated by Django 3.2.13 on 2022-11-29 08:11

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=160, validators=[articles.models.validate_text]),
        ),
    ]
