# Generated by Django 3.2.13 on 2022-12-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_declaration'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='declaration',
            constraint=models.UniqueConstraint(fields=('reporter', 'articles'), name='only_one_report'),
        ),
    ]
