# Generated by Django 3.2.13 on 2022-12-02 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('articles', '0003_alter_articles_music_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='music_url',
        ),
        migrations.AddField(
            model_name='articles',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.song'),
            preserve_default=False,
        ),
    ]
