# Generated by Django 3.2.13 on 2022-12-05 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_feelings'),
        ('articles', '0003_declaration_only_one_report'),
    ]

    operations = [
    ]
